Using streams
spring-projects/spring-petclinic pull request #1134
Opened 2023-01-02 05:12 UTC by IfeSunmola

Refactored some methods from using foreach loops to streams

2023-01-02 05:12 UTC, pivotal-cla commented
@IfeSunmola Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-petclinic&pullRequestId=1134)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-petclinic&pullRequestId=1134) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2023-01-02 05:13 UTC, pivotal-cla commented
@IfeSunmola Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-petclinic&pullRequestId=1134)!

2023-01-02 20:26 UTC, andrzejsydor requested changes

2023-01-02 20:26 UTC, andrzejsydor commented on src/main/java/org/springframework/samples/petclinic/owner/Owner.java
> +				.filter(pet -> pet.getName() != null && pet.getName().toLowerCase().equals(tempName))
you can use `equalsIgnoreCase`

2023-01-02 20:26 UTC, andrzejsydor commented on src/main/java/org/springframework/samples/petclinic/owner/PetTypeFormatter.java
> +		return owners.findPetTypes()
```suggestion
		return owners.findPetTypes().stream()
```

2023-01-27 09:54 UTC, dsyer commented
I'm not sure the stream API is any better for these tiny examples, and might even be worse - it just looks "clever" to me, not really self-documenting or anything useful. I'm tempted to just close this PR, but interested to hear other opinions.

2023-01-27 19:16 UTC, IfeSunmola commented
> I'm not sure the stream API is any better for these tiny examples, and might even be worse - it just looks "clever" to me, not really self-documenting or anything useful. I'm tempted to just close this PR, but interested to hear other opinions.

Hi, 

I'm assuming this project is somewhat directed towards people that are new to java and spring? If that's the case, isn't it better for them to know that streams exists, and see the usage? Anyone that has made it here probably knows how to use the good ol for loop. 

Streams have been around for a relatively long time and questions about it even comes up in interviews. I didn't know about them till like a year ago because almost every code on the internet is still stuck on for loops

2023-01-27 22:36 UTC, dsyer commented
And that’s kind of my point right there. The purpose of this project is definitely to educate, but the subject is Spring and Java, not the JDK. If for loops work and are understandable by a larger audience, that’s a good reason not to change anything. There really is no upside.

2023-03-10 08:12 UTC, closed without merging