Update readme file
spring-projects/spring-petclinic pull request #1223
Opened 2023-04-08 05:25 UTC by thienle3005

AB#333

2023-04-08 05:25 UTC, pivotal-cla commented
@thienle3005 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-petclinic&pullRequestId=1223)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-petclinic&pullRequestId=1223) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2023-04-08 14:58 UTC, andrzejsydor requested changes

2023-04-08 14:58 UTC, andrzejsydor commented on Jenkinsfile
> +          image 'maven:3.5.0'
why not to use the latest one?
https://hub.docker.com/layers/library/maven/3.9.1/images/sha256-dcfe7934d3780beda6e1f0f641bc7db3fa9b8818899981f6eddae052c78394c7?context=explore

2023-04-13 13:02 UTC, closed without merging

2023-04-13 13:02 UTC, dsyer commented
Spam?