Update pom.xml
spring-projects/spring-petclinic pull request #1266
Opened 2023-06-18 02:44 UTC by jay-awale

Added micrometer-prometheus-registry dependency

2023-06-18 02:44 UTC, pivotal-cla commented
@jay-awale Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-petclinic&pullRequestId=1266)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-petclinic&pullRequestId=1266) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2023-06-18 07:27 UTC, andrzejsydor commented on pom.xml
> +<dependency>
please format the code

2023-06-20 10:27 UTC, dsyer commented
We might be interested in prometheus, but does it add anything to the PetClinic? What features are we going to see?

2023-07-11 18:56 UTC, bichu1010 approved these changes

2023-07-12 14:49 UTC, andrzejsydor requested changes

2023-08-24 14:42 UTC, closed without merging