Fix typo in VetController.java
spring-projects/spring-petclinic pull request #1274
Opened 2023-06-27 05:22 UTC by jee14

Erasing unnecessary 1 line.

2023-06-27 05:22 UTC, pivotal-cla commented
@jee14 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-petclinic&pullRequestId=1274)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-petclinic&pullRequestId=1274) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2023-06-27 05:23 UTC, pivotal-cla commented
@jee14 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-petclinic&pullRequestId=1274)!

2023-06-27 12:06 UTC, andrzejsydor requested changes
rejected, there is no typo fixed

2023-07-05 10:34 UTC, dsyer commented
Kind of super picky, even by my standards. But that's fine.

2023-07-05 10:34 UTC, merged