Fix #1302 n+1 queries in owners
spring-projects/spring-petclinic pull request #1303
Opened 2023-07-24 18:33 UTC by tekshteint

When using the parameterless GET request on the /owners endpoint as well as searching for an empty string on the webpage for owners, the petclinic application ends up creating N+1 queries. This is due to the following code:

OwnerController.processFindForm
```
                if (owner.getLastName() == null) {
			owner.setLastName(""); // empty string signifies broadest possible search
		}

		
		Page<Owner> ownersResults = findPaginatedForOwnersLastName(page, owner.getLastName());
		if (ownersResults.isEmpty()) {
			// no owners found
			result.rejectValue("lastName", "notFound", "not found");
			return "owners/findOwners";
		}
```

This can be solved by adding a new query to the Owner Repository and updating the controller. These changes can be observed using [digma.ai](http://digma.ai/) as I've left the necessary imports/dependencies for Open Telemetry as well.

2023-08-24 14:57 UTC, dsyer commented
It's not a terrible idea, but maybe not really all that necessary (given that n=5). Anyway, if you would like to remove the otel stuff and squash and rebase to a single commit I will take another look.

2023-08-27 19:07 UTC, andrzejsydor approved these changes

2023-09-08 19:33 UTC, tekshteint commented
> 

Not a problem, sorry for the mess as I'm still new to Git but I hope that this should be more proper now.

Branches squashed and merged, OTEL has been removed and only the fix remains.

2023-09-12 09:55 UTC, dsyer commented
The changes to `build.gradle` are just whitespace right? So we don't need them. Also the build failed (error message tells you how to fix it).

2023-10-03 02:45 UTC, tekshteint commented
@dsyer Everything should be taken care of, thanks again for your patience with me.

2023-10-03 05:09 UTC, andrzejsydor requested changes
the commit message is different that the changes

2023-10-05 06:01 UTC, andrzejsydor approved these changes

2023-10-05 17:13 UTC, dsyer requested changes
Some more minor stuff to tweak.

2023-10-05 17:13 UTC, dsyer commented on src/main/java/org/springframework/samples/petclinic/owner/OwnerController.java
> +import org.thymeleaf.util.StringUtils;
Please use Spring's `StringUtils`.

2023-10-05 17:13 UTC, dsyer commented on src/main/java/org/springframework/samples/petclinic/owner/OwnerController.java
> +		model.addAttribute("listOwners", paginated);
"listOwners" is now added twice?

2023-10-05 17:13 UTC, dsyer commented on build.gradle
> +    id 'java'
Please get rid of whitespace changes (I don't think this file changed at all so you could just grab it from main).

2024-05-20 09:44 UTC, closed without merging