New pr
spring-projects/spring-petclinic pull request #1378
Opened 2023-10-16 19:13 UTC by brunoantognolli

test to new PR

2023-10-16 19:13 UTC, pivotal-cla commented
@brunoantognolli Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-petclinic&pullRequestId=1378)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-petclinic&pullRequestId=1378) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2023-10-17 05:19 UTC, andrzejsydor requested changes
Why so many commits?
What are the commit names about? -> could be improved

2023-10-17 05:19 UTC, andrzejsydor commented on src/test/java/org/springframework/samples/petclinic/TestNoord.java
> +	public void simpleTestTrue() {
```suggestion
	void simpleTestTrue() {
```

2023-10-17 05:19 UTC, andrzejsydor commented on src/test/java/org/springframework/samples/petclinic/TestNoord.java
> +public class TestNoord {
```suggestion
class TestNoord {
```

2023-10-17 08:00 UTC, mdeinum commented
Please remove this PR, don't use a public repository for your own learning use your own fork instead!

2023-10-17 13:15 UTC, closed without merging