My First CD /CD Deployment
spring-projects/spring-petclinic pull request #1381
Opened 2023-10-18 20:19 UTC by ProfAntonioFigueiredo

2023-10-18 20:19 UTC, pivotal-cla commented
@ProfAntonioFigueiredo Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-petclinic&pullRequestId=1381)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-petclinic&pullRequestId=1381) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2023-10-20 08:57 UTC, mdeinum commented
Please don't use a public repository for your own testing, learning use your own fork. Please remove this PR.

2023-10-20 15:49 UTC, andrzejsydor requested changes
What the PR is about?

2023-10-20 15:56 UTC, closed without merging

2023-10-20 15:57 UTC, ProfAntonioFigueiredo commented
Sorry for inconvenience